# One hot Encoder

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv(r"C:\Users\choudhary\Downloads\SBI loan dataset\SBI loan dataset\test_Y3wMUE5_7gLdaTN.csv")

In [3]:
dataset

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...
362,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777,113.0,360.0,1.0,Urban
363,LP002975,Male,Yes,0,Graduate,No,4158,709,115.0,360.0,1.0,Urban
364,LP002980,Male,No,0,Graduate,No,3250,1993,126.0,360.0,NaN,Semiurban
365,LP002986,Male,Yes,0,Graduate,No,5000,2393,158.0,360.0,1.0,Rural
366,LP002989,Male,No,0,Graduate,Yes,9200,0,98.0,180.0,1.0,Rural

In [4]:
dataset.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [24]:
dataset["Gender"] = dataset["Gender"].fillna(dataset["Gender"].mode()[0])

# mode lga kr fill kr do jo zyda h male aur female

In [25]:
dataset["Gender"].mode()

# male zyda h to khali jgha male aa jayengye

0    Male
Name: Gender, dtype: object

In [6]:
dataset.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [7]:
en_data = dataset[["Gender","Married"]]

In [26]:
pd.get_dummies(en_data)
pd.get_dummies(en_data).info()

# ab do column ko alg alg dummies table bana lo

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  367 non-null    bool
 1   Gender_Male    367 non-null    bool
 2   Married_No     367 non-null    bool
 3   Married_Yes    367 non-null    bool
dtypes: bool(4)
memory usage: 1.6 KB

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
ohe = OneHotEncoder()

In [11]:
ohe.fit_transform(en_data)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 734 stored elements and shape (367, 4)>

In [12]:
ohe = OneHotEncoder()
ohe.fit_transform(en_data).toarray()

array([[0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       ...,
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.]], shape=(367, 4))

In [13]:
ohe = OneHotEncoder()
ar = ohe.fit_transform(en_data).toarray()

In [14]:
pd.DataFrame(ar,columns=["Gender_Female","Gender_Male","Married_No","Married_Yes"])

     Gender_Female  Gender_Male  Married_No  Married_Yes
0              0.0          1.0         0.0          1.0
1              0.0          1.0         0.0          1.0
2              0.0          1.0         0.0          1.0
3              0.0          1.0         0.0          1.0
4              0.0          1.0         1.0          0.0
..             ...          ...         ...          ...
362            0.0          1.0         0.0          1.0
363            0.0          1.0         0.0          1.0
364            0.0          1.0         1.0          0.0
365            0.0          1.0         0.0          1.0
366            0.0          1.0         1.0          0.0

[367 rows x 4 columns]

In [15]:
ohe = OneHotEncoder(drop = "first")
ar = ohe.fit_transform(en_data).toarray()

In [17]:
pd.DataFrame(ar,columns=["Gender","Married"])

     Gender  Married
0       1.0      1.0
1       1.0      1.0
2       1.0      1.0
3       1.0      1.0
4       1.0      0.0
..      ...      ...
362     1.0      1.0
363     1.0      1.0
364     1.0      0.0
365     1.0      1.0
366     1.0      0.0

[367 rows x 2 columns]